### ISSUE TITLE
Issue of "This feature does not support pyodide runtime!"

### ISSUE THREAD

**Issue by MRYingLEE** [promplate/pyodide#2]
I tried your playground and I always met the issue regardless I used my own OpenAI key or your one.

```Python
complete = ChatComplete(base_url="https://promplate.dev", api_key="").bind(model="gpt-3.5-turbo-0125")

complete("hi")

This feature does not support pyodide runtime!
```

Maybe your document is outdated.

Please clarify.

**Comment by CNSeniorious000** [comment]
Sorry for confusing and thanks for reporting! tl;dr, `promplate` support both sync and async usages, and the online playground only supports the async ones, so if you use the sync ones it will display this error message.

The online python playground use `fetch` from JavaScript to invoke web requests, but `fetch` is async, so sync primitives of llms won't work in the online playground. If you try `promplate.ChatComplete` in your local machine in your python console or jupyter notebooks, it will work.

In the online playground, if you click the 🚀 button to run example code, it should automatically convert all sync API calls into async ones. So I suppose you copied and pasted them in the playground. If you just click the 🚀 button everything would works well. Or you can paste the code into your local python console.

Feel free to ask anything!

**Comment by MRYingLEE** [comment]
I just couldn't your mentioned 🚀 button.
![image](https://github.com/user-attachments/assets/b7517050-7793-48d2-b172-819f4a1e7577)

Can you share a captured screen?

**Comment by CNSeniorious000** [comment]
On [the homepage](https://promplate.dev/py):

![image](https://github.com/user-attachments/assets/661314f9-f4eb-4f42-a2ea-5e6385a21b4e)

On the [interactive quick start](https://promplate.dev/py/quick-start):

![image](https://github.com/user-attachments/assets/1f5d26e8-d2ca-4735-b4f9-3fbedc6d85e1)

**Comment by CNSeniorious000** [comment]
After #5, you can [try the sync APIs on py3.online](https://py3.online/console#ZnJvbSBtaWNyb3BpcCBpbXBvcnQgaW5zdGFsbAphd2FpdCBpbnN0YWxsKCJwcm9tcGxhdGUtcHlvZGlkZSIpCgpmcm9tIHByb21wbGF0ZV9weW9kaWRlIGltcG9ydCBwYXRjaF9hbGwKYXdhaXQgcGF0Y2hfYWxsKCkKCmZyb20gcHJvbXBsYXRlLmxsbS5vcGVuYWkgaW1wb3J0IENoYXRDb21wbGV0ZQpjaGF0ID0gQ2hhdENvbXBsZXRlKCkKY2hhdAoKY2hhdCgiaGkiLCBtb2RlbD0iZ2VtbWEyLTliLWl0IikK) now. No more confusing message~
